git:
  commitMessage: 'chore: release v${version}'
  pushArgs: ['--follow-tags', '--force']
github:
  release: true
  releaseName: 'Release v${version}'
  tokenRef: RELEASE_GITHUB_TOKEN
npm:
  publish: false
  skipChecks: true
plugins:
  '@release-it/conventional-changelog':
    infile: CHANGELOG.md
    preset:
      name: conventionalcommits
